### PR TITLE
Fix some errors

### PR DESCRIPTION
**Pull request by dalcde**
I'll undraft this when all tests pass (or it is clear that much more work is needed to make all tests pass)

### CODE REVIEW

**Comment by dalcde** [comment]
I am getting errors
```
        for import_name in meta.get("test", {}).get("imports", []):

            if name not in loaded_packages:
                selenium_standalone.load_package(name)
                loaded_packages.append(name)
            try:
>               selenium_standalone.run("import %s" % import_name)

E       selenium.common.exceptions.WebDriverException: Message: unknown error: memory access out of bounds
E         (Session info: headless chrome=83.0.4103.116)
E         (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 5.9.10-arch1-1 x86_64)

/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```
for `chrome-lxml`, `chrome-astropy` and `chrome-mne` in `src/tests/test_common.py`.

EDIT: These don't happen consistently.

**Comment by dalcde** [comment]
I sometimes get the following error:
`test_scipy`: `test_brentq[firefox]`
```

    def test_brentq(selenium_standalone):
        selenium_standalone.load_package("scipy")
>       selenium_standalone.run("from scipy.optimize import brentq")

E       selenium.common.exceptions.JavascriptException: Message: Error: Traceback (most recent call last):
E         File "/lib/python3.8/site-packages/pyodide.py", line 66, in eval_code
E           exec(compile(mod, "<exec>", mode="exec"), ns, ns)
E         File "<exec>", line 1, in <module>
E       ModuleNotFoundError: No module named 'scipy'
```
as well as the memory access out of bounds error with `test_brentq[chrome]`.

**Comment by dalcde** [comment]
The only consistently reproducible error is `test_cpython_core[test_compile-chrome]`. Some relevant logs:
```
ERROR: test_extended_arg (test.test_compile.TestSpecifics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/lib/python3.8/test/test_compile.py", line 128, in test_extended_arg
    exec(code, g)
RecursionError: maximum recursion depth exceeded during compilation

----------------------------------------------------------------------

Ran 73 tests in 2.370s

FAILED (errors=1, skipped=2)
test test_compile failed
test_compile failed

== Tests result: FAILURE ==

1 test failed:
    test_compile
```
I think the PR can be merged and this can be sorted out later.

**Comment by dalcde** [comment]
Of course the test can be made to pass by simply increasing the recursion limit, but I don't know if we want to do that.

**Comment by rth** [comment]
Thanks! I gave you write access to my fork, so don't hesitate to push commits to https://github.com/iodide-project/pyodide/pull/480 directly.

> as well as the memory access out of bounds error with test_brentq[chrome].

Yes, those also happen occasionally on master in Chrome https://github.com/iodide-project/pyodide/issues/729 so it's not an immediate concern.

> Of course the test can be made to pass by simply increasing the recursion limit, but I don't know if we want to do that.

yes, that part is a bit brittle. We already have a fix for the recursion limit in https://github.com/iodide-project/pyodide/blob/09d56a2d6429801e8954576d560db59637d176ce/src/pyodide.js#L273 but it's true that I have seen this error occasionally in the past.

**Pull request merged**
